version: '3.3'
services:
  nginx:
    build: ../dockerfile/nginx-1.15.5
    ports:
      - "80:80" #nginx
    restart: always
    tty: true
    container_name: nginx
    volumes:
      - D:\Alex\data\www:/var/www/html
      - D:\Alex\data\logs\nginx:/var/log/nginx
      - D:\Alex\data\docker\config\nginx\conf.d:/etc/nginx/conf.d
      - D:\Alex\data\docker\config\nginx\nginx.conf:/etc/nginx/nginx.conf
      - D:\Alex\data\etc\letsencrypt:/etc/letsencrypt
    networks:
     - lnmp-networks
  php7:
    build: ../dockerfile/php-7.2-fpm
    tty: true
    restart: always
    container_name: php7
    volumes:
      - D:\Alex\data\www:/var/www/html
      - D:\Alex\data\logs\php:/var/log/php
      - D:\Alex\data\docker\config\php\php.ini:/usr/local/etc/php/php.ini
      - D:\Alex\data\docker\config\php\www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - nginx
    networks:
     - lnmp-networks
  redis:
    build: ../dockerfile/redis-5.0.5
    container_name: redis
    tty: true
    restart: always
    volumes:
      - D:\Alex\data\docker\config\redis\redis.conf:/etc/redis/redis.conf
      - D:\Alex\data\redis:/var/lib/redis
      - D:\Alex\data\logs\redis:/var/log/redis
    networks:
     - lnmp-networks
  mysql:
    build: ../dockerfile/mysql-8.0.18
    container_name: mysql
    tty: true
    restart: always
    ports:
      - "3306:3306" #mysql
    volumes:
      - D:\Alex\data\mysql:/var/lib/mysql
      - D:\Alex\data\docker\config\mysql\mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - D:\Alex\data\logs\mysql:/var/log/mysql
      - D:\Alex\data\mysqlback:/data/mysqlback
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - lnmp-networks  
networks:
 lnmp-networks:
